## YAML Template.
---
server:
  port: 9006

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: anggotaservice
            uri: lb://anggotaservice
            predicates:
              - Path=api/anggota/
          - id: bukuservice
            uri: lb://bukuservice
            predicates:
              - Path=api/buku
          - id: peminjamanservice
            uri: lb://PEMINJAMAN-SERVICE
            predicates:
              - Path=api/peminjaman
              - Method=POST,PUT,DELETE
          - id: pengembalianservice
            uri: lb://PENGEMBALIAN-SERVICE
            predicates:
              - Path=api/pengembalian
          # - id: peminjamanqueryservice
          #   uri: lb://peminjamanqueryservice
          #   predicates:
          #     - Path=/api/peminjaman/**
          #     - Method=GET

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
