## YAML Template.
---
server:
  port: 9006

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: ANGGOTASERVICE
            uri: lb://ANGGOTASERVICE
            predicates:
              - Path=api/anggota/**
          - id: BUKUSERVICE
            uri: lb://BUKUSERVICE
            predicates:
              - Path=api/buku/**
          - id: PEMINJAMANSERVICE
            uri: lb://PEMINJAMANSERVICE
            predicates:
              - Path=api/peminjaman/**
              - Method=POST,PUT,DELETE
          - id: PENGEMBALIANSERVICE
            uri: lb://PENGEMBALIANSERVICE
            predicates:
              - Path=api/pengembalian/**
          - id: PEMINJAMANQUERYSERVICE
            uri: lb://PEMINJAMANQUERYSERVICE
            predicates:
              - Path=api/peminjaman/**
              - Method=GET

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
